In [1]:
import pandas as pd
import numpy as np

cust = pd.read_csv('../sc_cust_info_txn_v1.5.csv')
cust

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
0,202006,20200630,10001,C,F,28,0,N,N,2640.0000,792.000000,1584.0000,0.0,0.0000,Y
1,202006,20200630,10001,_,_,_,1,N,N,300.0000,90.000000,180.0000,0.0,0.0000,Y
2,202006,20200630,10001,E,F,24,1,N,N,16840.0000,2526.000000,6983.0000,0.0,6981.0000,N
3,202006,20200630,10001,F,F,32,1,N,N,15544.7334,2331.710010,6750.4666,0.0,6508.8000,N
4,202006,20200630,10001,D,M,18,1,N,N,4700.0000,0.000000,4502.0000,0.0,4507.7000,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9925,202006,20200630,10001,C,F,15,1,N,Y,1296.0999,194.414985,643.1001,0.0,852.5499,N
9926,202006,20200630,10001,G,M,12,1,N,N,13799.6666,2069.949990,10605.9266,0.0,10603.9266,N
9927,202006,20200630,10005,C,_,_,1,N,N,1396.2000,1206.000000,0.0000,1212.0,0.0000,N
9928,202006,20200630,10001,C,F,40,0,N,N,3140.0000,942.000000,1884.0000,0.0,0.0000,Y
9929,202006,20200630,10001,C,F,59,1,N,N,2436.9000,365.535000,1839.9000,0.0,1919.7999,N

In [ ]:
# 데이터 살펴보기

## head
cust.head()
cust.head(n=3)

## tail
cust.tail()
cust.tail(n=3)

## shape (row 개수, col 개수)
cust.shape # (9930, 15)

## columns
cust.columns
# Index(['base_ym', 'dpro_tgt_perd_val', 'cust_ctg_type', 'cust_class',
#        'sex_type', 'age', 'efct_svc_count', 'dt_stop_yn', 'npay_yn',
#        'r3m_avg_bill_amt', 'r3m_A_avg_arpu_amt', 'r3m_B_avg_arpu_amt',
#        'r6m_A_avg_arpu_amt', 'r6m_B_avg_arpu_amt', 'termination_yn'],
#       dtype='str')

## index
cust.index # RangeIndex(start=0, stop=9930, step=1)
cust.index.values # array([   0,    1,    2, ..., 9927, 9928, 9929])
cust.values
# array([[202006, 20200630, 10001, ..., 0.0, 0.0, 'Y'],
#        [202006, 20200630, 10001, ..., 0.0, 0.0, 'Y'],
#        [202006, 20200630, 10001, ..., 0.0, 6981.0, 'N'],
#        ...,
#        [202006, 20200630, 10005, ..., 1212.0, 0.0, 'N'],
#        [202006, 20200630, 10001, ..., 0.0, 0.0, 'Y'],
#        [202006, 20200630, 10001, ..., 0.0, 1919.7999, 'N']], dtype=object)

## info
cust.info()
# <class 'pandas.DataFrame'>
# RangeIndex: 9930 entries, 0 to 9929
# Data columns (total 15 columns):
#  #   Column              Non-Null Count  Dtype  
# ---  ------              --------------  -----  
#  0   base_ym             9930 non-null   int64  
#  1   dpro_tgt_perd_val   9930 non-null   int64  
#  2   cust_ctg_type       9930 non-null   int64  
#  3   cust_class          9930 non-null   str    
#  4   sex_type            9930 non-null   str    
#  5   age                 9930 non-null   str    
#  6   efct_svc_count      9930 non-null   int64  
#  7   dt_stop_yn          9930 non-null   str    
#  8   npay_yn             9930 non-null   str    
#  9   r3m_avg_bill_amt    9930 non-null   float64
#  10  r3m_A_avg_arpu_amt  9930 non-null   float64
#  11  r3m_B_avg_arpu_amt  9930 non-null   float64
#  12  r6m_A_avg_arpu_amt  9930 non-null   float64
#  13  r6m_B_avg_arpu_amt  9930 non-null   float64
#  14  termination_yn      9930 non-null   str    
# dtypes: float64(5), int64(4), str(6)
# memory usage: 1.1 MB

## describe (개수, 평균, 표준편차, 최소값, 1분위, 중간값, 3분위, 최대값 제공)
cust.describe()

## dtypes
cust.dtypes
# base_ym                 int64
# dpro_tgt_perd_val       int64
# cust_ctg_type           int64
# cust_class                str
# sex_type                  str
# age                       str
# efct_svc_count          int64
# dt_stop_yn                str
# npay_yn                   str
# r3m_avg_bill_amt      float64
# r3m_A_avg_arpu_amt    float64
# r3m_B_avg_arpu_amt    float64
# r6m_A_avg_arpu_amt    float64
# r6m_B_avg_arpu_amt    float64
# termination_yn            str
# dtype: object

<class 'pandas.DataFrame'>
RangeIndex: 9930 entries, 0 to 9929
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   base_ym             9930 non-null   int64
 1   dpro_tgt_perd_val   9930 non-null   int64
 2   cust_ctg_type       9930 non-null   int64
 3   cust_class          9930 non-null   str
 4   sex_type            9930 non-null   str
 5   age                 9930 non-null   str
 6   efct_svc_count      9930 non-null   int64
 7   dt_stop_yn          9930 non-null   str
 8   npay_yn             9930 non-null   str
 9   r3m_avg_bill_amt    9930 non-null   float64
 10  r3m_A_avg_arpu_amt  9930 non-null   float64
 11  r3m_B_avg_arpu_amt  9930 non-null   float64
 12  r6m_A_avg_arpu_amt  9930 non-null   float64
 13  r6m_B_avg_arpu_amt  9930 non-null   float64
 14  termination_yn      9930 non-null   str
dtypes: float64(5), int64(4), str(6)
memory usage: 1.1 MB

base_ym                 int64
dpro_tgt_perd_val       int64
cust_ctg_type           int64
cust_class                str
sex_type                  str
age                       str
efct_svc_count          int64
dt_stop_yn                str
npay_yn                   str
r3m_avg_bill_amt      float64
r3m_A_avg_arpu_amt    float64
r3m_B_avg_arpu_amt    float64
r6m_A_avg_arpu_amt    float64
r6m_B_avg_arpu_amt    float64
termination_yn            str
dtype: object

In [18]:
# 데이터 조회하기

## 단일 조회
# 1. 하나의 컬럼(cust_class)의 데이터 조회 1 (Series 형태로 조회)
cust.cust_class

# 2. 하나의 컬럼의 데이터 조회 2 (Series 형태로 조회)
cust['cust_class']

# 3. 하나의 컬럼의 데이터 조회 3 (Dataframe 형태로 조회)
cust[['cust_class']]

## 복수 조회
cust[['cust_class', 'age', 'r3m_avg_bill_amt']]

     cust_class age  r3m_avg_bill_amt
0             C  28         2640.0000
1             _   _          300.0000
2             E  24        16840.0000
3             F  32        15544.7334
4             D  18         4700.0000
...         ...  ..               ...
9925          C  15         1296.0999
9926          G  12        13799.6666
9927          C   _         1396.2000
9928          C  40         3140.0000
9929          C  59         2436.9000

[9930 rows x 3 columns]

In [ ]:
# DataFrame slicing

## 범위 설정
cust[7:10]

## 단일 인덱스 접근
# cust[7] # 불가능, 에러 반환
cust[7:8] # 가능, row 접근

## 단일 컬럼 접근
cust['base_ym'] # 가능
cust['base_ym'][7] # 단일 인덱스는 단일 컬럼 선택 후 가능

202006

In [49]:
# row 선택하기

## arrange
cp = np.arange(10, 20)
cp # array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## index 달기
cust.index # 기본 인덱스는 0 ~ 9929
cust.index = np.arange(100, 10030)
cust.index # 신규 인덱스는 100 ~ 10029
# Index([  100,   101,   102,   103,   104,   105,   106,   107,   108,   109,
#        ...
#        10020, 10021, 10022, 10023, 10024, 10025, 10026, 10027, 10028, 10029],
#       dtype='int64', length=9930)

cust.head() # 인덱스가 100부터 시작되는 것을 확인할 수 있다.
cust.tail() # 인덱스가 10029로 마무리되는 것을 확인할 수 있다.

## loc - row 가져오기 (설정한 index 기준, 사람 기준)
# 한 개의 row 가져오기 (Series 방식)
cust.loc[10028]
# 한 개의 row 가져오기 (DataFrames 방식)
cust.loc[[10028]]
# 여러 개의 row 가져오기
cust.loc[[102, 202, 302]]

## iloc - row 가져오기 (절대 index 기준, 컴퓨터 기준)
cust.iloc[[2, 102, 202]]

## 행렬 동시 선택하기 (loc, iloc)
# 단일 (row, col 순)
cust.loc[102, 'age']
# 복수 (row, col 순)
cust.loc[[100, 200, 300], ['cust_class', 'sex_type', 'age', 'r3m_avg_bill_amt', 'r3m_A_avg_arpu_amt']]
cust.iloc[[0, 100, 200], [3, 4, 5, 9, 10]] # 상위 loc와 동일한 결과

## 조건으로 row 선택하기
# 예시 1: 남자인 사람만 row 선택하기
condition1 = cust['sex_type'] == 'M'
cust[condition1]
# 예시 2: 남자이면서 3개월 평균 청구 금액이 50000 이상이면서 100000 미만인 사람인 row 선택하기
condition2 = (cust['r3m_avg_bill_amt'] >= 50000) & (cust['r3m_avg_bill_amt'] < 100000)
cust[condition1 & condition2].head(3)

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
472,202006,20200630,10001,F,M,28,1,N,N,65113.66670,1310.4000,20083.5033,0.0,19426.1983,N
1149,202006,20200630,10001,D,M,20,2,N,N,80335.67685,69136.1001,3896.3334,0.0,3727.6666,N
1464,202006,20200630,10001,_,M,45,1,N,Y,54865.70000,2321.8666,8744.9382,0.0,8774.7162,N

In [ ]:
# 데이터 추가, 삭제하기

## 새로룬 column 추가하기
# 예시: r3m_avg_bill_amt를 두 배로 하는 col 추가
cust['r3m_avg_bill_amt2'] = cust['r3m_avg_bill_amt'] * 2
cust.head()

## column 삭제하기
# 단일 삭제 (cust의 행이 삭제되지는 않음)
cust.drop('r3m_avg_bill_amt2', axis=1) # axis=0가 default, 0일 경우 col이 아니라 row를 삭제)

# 제거된 데이터 사용
cust1 = cust.drop('r3m_avg_bill_amt2', axis=1)
cust1.head()

# 원본 데이터 제거 사용
cust.drop('r3m_avg_bill_amt2', axis=1, inplace=True)

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
100,202006,20200630,10001,C,F,28,0,N,N,2640.0000,792.00000,1584.0000,0.0,0.0,Y
101,202006,20200630,10001,_,_,_,1,N,N,300.0000,90.00000,180.0000,0.0,0.0,Y
102,202006,20200630,10001,E,F,24,1,N,N,16840.0000,2526.00000,6983.0000,0.0,6981.0,N
103,202006,20200630,10001,F,F,32,1,N,N,15544.7334,2331.71001,6750.4666,0.0,6508.8,N
104,202006,20200630,10001,D,M,18,1,N,N,4700.0000,0.00000,4502.0000,0.0,4507.7,N