# 실습 1

- 아래의 2개의 리스트를 활용하여 질문에 답하라.
```
data1 = [
         ['홍길동',23,'남'],
         ['이순신',55,'남']
]

data2 = [
         ['신사임당',48,'여'], 
         ['장보고',22,'남']
]
```

In [4]:
import pandas as pd
import numpy as np

data1 = [
         ['홍길동',23,'남'],
         ['이순신',55,'남']
]

data2 = [
         ['신사임당',48,'여'], 
         ['장보고',22,'남']
]
# 컬럼명은 이름, 나이, 성별로 설정하기

df1 = pd.DataFrame(data1, columns=['이름', '나이', '성별'])
df2 = pd.DataFrame(data2, columns=['이름', '나이', '성별'])

# 1. df1, df2 데이터프레임을 위 아래로 합치기
pd.concat([df1, df2])
# 2. df1, df2 데이터프레임을 인덱스를 새로 만들어서 위 아래로 합치기
pd.concat([df1, df2], ignore_index=True)

     이름  나이 성별
0   홍길동  23  남
1   이순신  55  남
2  신사임당  48  여
3   장보고  22  남

실습 2

- 아래 리스트를 활용하여 질문에 답하라.
```
data1 = [
         [23,'남'],
         [55,'남'], 
         [48,'여']
]

columns = ['나이','성별']
index = ['홍길동','이순신','신사임당']


data2 = [
         ['서울',3], 
         ['경기', 1]
]

columns = ['주소','학년']
index = ['홍길동','신사임당']
```

In [12]:
import pandas as pd

data1 = [
         [23,'남'],
         [55,'남'], 
         [48,'여']
]

columns1 = ['나이','성별']
index1 = ['홍길동','이순신','신사임당']


data2 = [
         ['서울', 3], 
         ['경기', 1]
]

columns2 = ['주소','학년']
index2 = ['홍길동','신사임당']

df1 = pd.DataFrame(data1, columns=columns1, index=index1)
df2 = pd.DataFrame(data2, columns=columns2, index=index2)

# 1. df1, df2 데이터프레임을 활용해서 왼쪽, 오른쪽으로 합치기
pd.concat([df1, df2], axis=1)

      나이 성별   주소   학년
홍길동   23  남   서울  3.0
이순신   55  남  NaN  NaN
신사임당  48  여   경기  1.0

# 실습 3

- 아래 리스트를 활용하여 질문에 답하라.
```
data1 = [
         ['홍길동',23,'남'],
         ['이순신',55,'남'], 
         ['신사임당',48,'여']
]

columns=['이름','나이','성별']

data2 = [
         ['홍길동','터미네이터',5],
         ['홍길동','비긴어게인',2], 
         ['홍길동','살인의추억',4], 
         ['신사임당','비긴어게인',5],
         ['장보고','살인의추억',3]
]

columns=['이름','나이','성별']
```

In [ ]:
import pandas as pd

data1 = [
         ['홍길동',23,'남'],
         ['이순신',55,'남'], 
         ['신사임당',48,'여']
]

columns1=['이름','나이','성별']

data2 = [
         ['홍길동','터미네이터',5],
         ['홍길동','비긴어게인',2], 
         ['홍길동','살인의추억',4], 
         ['신사임당','비긴어게인',5],
         ['장보고','살인의추억',3]
]

columns2=['이름','영화','평점']

df1 = pd.DataFrame(data=data1, columns=columns1)
df2 = pd.DataFrame(data=data2, columns=columns2)

# 1. df1 데이터프레임 보기
df1
# 2. df2 데이터프레임 보기
df2
# 3. 이름 컬럼을 key로 해서 교집합 merge (df3로 할당)
df3 = pd.merge(df1, df2, on='이름')
# 4. 이름 컬럼을 key로 해서 df1 기준 merge
pd.merge(df1, df2, on='이름', how='left')
# 5. 이름 컬럼을 key로 해서 df2 기준 merge
pd.merge(df1, df2, on='이름', how='right')
# 6. 이름 컬럼을 key로 해서 합집합 merge
# pd.merge(df1, df2, on='이름', how='outer')
df1.merge(df2, on='이름', how='outer')

# 7. df3에서 이름별, 영화별 평점의 합 구하기
# df3.groupby(['이름', '영화'])['평점'].sum() # 결과만 빠르게 알고 싶을 때
pd.pivot_table(data=df3, index='이름', columns='영화', values='평점', aggfunc=np.sum) # 결과를 표로 깔끔하게 보고싶을 때

영화    비긴어게인  살인의추억  터미네이터
이름
신사임당    5.0    NaN    NaN
홍길동     2.0    4.0    5.0